export const chats = [
  {
    id: 1,
    users: [1, 2],
    messages: [
      { id: 1, senderId: 1, content: "hej masz notatki?", time: "10:00" },
      { id: 2, senderId: 2, content: "tak", time: "10:01" },
      { id: 3, senderId: 1, content: "podeślesz?", time: "10:02" },
      { id: 4, senderId: 2, content: "zaraz", time: "10:03" },
      { id: 5, senderId: 2, content: "wysłane", time: "10:04" },
      { id: 6, senderId: 1, content: "dzięki", time: "10:05" },
      { id: 7, senderId: 2, content: "spoko", time: "10:06" },
      { id: 8, senderId: 1, content: "ogarnąłeś temat?", time: "10:07" },
      { id: 9, senderId: 2, content: "średnio", time: "10:08" },
      { id: 10, senderId: 1, content: "same", time: "10:09" },
      { id: 11, senderId: 2, content: "xd", time: "10:10" },
      { id: 12, senderId: 1, content: "idziemy jutro?", time: "10:11" },
      { id: 13, senderId: 2, content: "no", time: "10:12" },
      { id: 14, senderId: 1, content: "git", time: "10:13" },
      { id: 15, senderId: 2, content: "to do zobaczenia", time: "10:14" },
      { id: 16, senderId: 1, content: "nara", time: "10:15" },
      { id: 17, senderId: 2, content: "nara", time: "10:16" },
      { id: 18, senderId: 1, content: "ej", time: "10:17" },
      { id: 19, senderId: 2, content: "?", time: "10:18" },
      { id: 20, senderId: 1, content: "nic", time: "10:19" },
    ],
  },

  {
    id: 2,
    users: [1, 3],
    messages: [
      { id: 1, senderId: 3, content: "pracujesz dziś?", time: "08:00" },
      { id: 2, senderId: 1, content: "tak", time: "08:01" },
      { id: 3, senderId: 3, content: "do której", time: "08:02" },
      { id: 4, senderId: 1, content: "16", time: "08:03" },
      { id: 5, senderId: 3, content: "ok", time: "08:04" },
      { id: 6, senderId: 1, content: "a ty?", time: "08:05" },
      { id: 7, senderId: 3, content: "też", time: "08:06" },
      { id: 8, senderId: 1, content: "fajnie", time: "08:07" },
      { id: 9, senderId: 3, content: "xd", time: "08:08" },
      { id: 10, senderId: 1, content: "co robisz potem", time: "08:09" },
      { id: 11, senderId: 3, content: "nie wiem", time: "08:10" },
      { id: 12, senderId: 1, content: "to coś wymyślimy", time: "08:11" },
      { id: 13, senderId: 3, content: "ok", time: "08:12" },
      { id: 14, senderId: 1, content: "pisz", time: "08:13" },
      { id: 15, senderId: 3, content: "piszę", time: "08:14" },
      { id: 16, senderId: 1, content: "haha", time: "08:15" },
      { id: 17, senderId: 3, content: "no co", time: "08:16" },
      { id: 18, senderId: 1, content: "nic", time: "08:17" },
      { id: 19, senderId: 3, content: "ok", time: "08:18" },
      { id: 20, senderId: 1, content: "dobra", time: "08:19" },
    ],
  },

  {
    id: 3,
    users: [1, 4],
    messages: [
      { id: 1, senderId: 1, content: "gramy?", time: "20:00" },
      { id: 2, senderId: 4, content: "gramy", time: "20:01" },
      { id: 3, senderId: 1, content: "wchodzisz?", time: "20:02" },
      { id: 4, senderId: 4, content: "już", time: "20:03" },
      { id: 5, senderId: 1, content: "ok", time: "20:04" },
      { id: 6, senderId: 4, content: "zapraszaj", time: "20:05" },
      { id: 7, senderId: 1, content: "wysłane", time: "20:06" },
      { id: 8, senderId: 4, content: "mam", time: "20:07" },
      { id: 9, senderId: 1, content: "start", time: "20:08" },
      { id: 10, senderId: 4, content: "lecimy", time: "20:09" },
      { id: 11, senderId: 1, content: "xd", time: "20:10" },
      { id: 12, senderId: 4, content: "lol", time: "20:11" },
      { id: 13, senderId: 1, content: "ale lagi", time: "20:12" },
      { id: 14, senderId: 4, content: "no masakra", time: "20:13" },
      { id: 15, senderId: 1, content: "padłem", time: "20:14" },
      { id: 16, senderId: 4, content: "ja też", time: "20:15" },
      { id: 17, senderId: 1, content: "jeszcze raz", time: "20:16" },
      { id: 18, senderId: 4, content: "dawaj", time: "20:17" },
      { id: 19, senderId: 1, content: "ok", time: "20:18" },
      { id: 20, senderId: 4, content: "go", time: "20:19" },
    ],
  },

  {
    id: 4,
    users: [1, 5],
    messages: [
      { id: 1, senderId: 5, content: "zamówiłeś jedzenie?", time: "18:00" },
      { id: 2, senderId: 1, content: "jeszcze nie", time: "18:01" },
      { id: 3, senderId: 5, content: "to zamów", time: "18:02" },
      { id: 4, senderId: 1, content: "co chcesz", time: "18:03" },
      { id: 5, senderId: 5, content: "pizza", time: "18:04" },
      { id: 6, senderId: 1, content: "ok", time: "18:05" },
      { id: 7, senderId: 5, content: "z szynką", time: "18:06" },
      { id: 8, senderId: 1, content: "git", time: "18:07" },
      { id: 9, senderId: 5, content: "i cola", time: "18:08" },
      { id: 10, senderId: 1, content: "ok", time: "18:09" },
      { id: 11, senderId: 5, content: "dzięki", time: "18:10" },
      { id: 12, senderId: 1, content: "spoko", time: "18:11" },
      { id: 13, senderId: 5, content: "kiedy będzie", time: "18:12" },
      { id: 14, senderId: 1, content: "za 30 min", time: "18:13" },
      { id: 15, senderId: 5, content: "ok", time: "18:14" },
      { id: 16, senderId: 1, content: "czekamy", time: "18:15" },
      { id: 17, senderId: 5, content: "głodny jestem", time: "18:16" },
      { id: 18, senderId: 1, content: "ja też", time: "18:17" },
      { id: 19, senderId: 5, content: "xd", time: "18:18" },
      { id: 20, senderId: 1, content: "lol", time: "18:19" },
    ],
  },

  {
    id: 5,
    users: [1, 6],
    messages: [
      { id: 1, senderId: 1, content: "robisz projekt?", time: "14:00" },
      { id: 2, senderId: 6, content: "tak", time: "14:01" },
      { id: 3, senderId: 1, content: "na jakim etapie", time: "14:02" },
      { id: 4, senderId: 6, content: "frontend", time: "14:03" },
      { id: 5, senderId: 1, content: "też", time: "14:04" },
      { id: 6, senderId: 6, content: "ciężko", time: "14:05" },
      { id: 7, senderId: 1, content: "trochę", time: "14:06" },
      { id: 8, senderId: 6, content: "ale damy radę", time: "14:07" },
      { id: 9, senderId: 1, content: "no", time: "14:08" },
      { id: 10, senderId: 6, content: "deadline blisko", time: "14:09" },
      { id: 11, senderId: 1, content: "wiem", time: "14:10" },
      { id: 12, senderId: 6, content: "xd", time: "14:11" },
      { id: 13, senderId: 1, content: "robimy dziś?", time: "14:12" },
      { id: 14, senderId: 6, content: "tak", time: "14:13" },
      { id: 15, senderId: 1, content: "ok", time: "14:14" },
      { id: 16, senderId: 6, content: "wieczorem", time: "14:15" },
      { id: 17, senderId: 1, content: "pasuje", time: "14:16" },
      { id: 18, senderId: 6, content: "to pisz", time: "14:17" },
      { id: 19, senderId: 1, content: "napiszę", time: "14:18" },
      { id: 20, senderId: 6, content: "ok", time: "14:19" },
    ],
  },
];